sudo: required
services:
  - docker

before_install:
  - docker build -t hwlassow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hwlassow/react-test npm test -- --coverage

after_success:
  - docker build -t hwlassow/multi-client ./client
  - docker build -t hwlassow/multi-nginx ./nginx
  - docker build -t hwlassow/multi-server ./server
  - docker build -t hwlassow/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push hwlassow/multi-client
  - docker push hwlassow/multi-nginx
  - docker push hwlassow/multi-server
  - docker push hwlassow/multi-worker
  
